import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import Image from "next/image"
import myImage from "../../public/frontend_image/my_image.jpg";
import Fiverfavicon from "../../public/frontend_image/favicon.ico";
import GithubIcon from "../../public/frontend_image/favicon-dark.png";
import Facebook from "../../public/frontend_image/facebook.ico";
import Instagram from "../../public/frontend_image/instagrame.ico"
import Link from "next/link";
import Hamburger from "../../public/frontend_image/burger.png"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
      // ${geistSans.variable} antialiased ${geistMono.variable}
        className={` text-white bg-black`}
      >

        <div className="w-[100%] h-[100vh] gap-2 relative px-2 flex items-center">
          <div className="w-[350px] gap-y-2 absolute md:static z-50 md:translate-x-0 translate-x-[-500px] rounded-lg bg-[#27272A] h-[90vh]">
            <div className="w-[160px] h-[160px] overflow-hidden m-auto mt-4 rounded-2xl hover:shadow-[0_20px_50px_rgba(8,_112,_184,_0.7)] transition-all duration-150 ">
              <Image src={myImage} className="h-full w-full" alt="my image" />
            </div>
            <div className="flex mt-8 gap-y-2 w-full flex-col list-none">
              <li className="w-[90%] m-auto h-12 rounded-md flex items-center text-[#ffffff] justify-center bg-[#212121] ">Musfikur Rahman</li>
              <a target="_blank" href={"https://www.facebook.com/tamim.jarry.99"} className="flex px-2 items-center gap-x-2 w-[90%] m-auto h-10 rounded-md bg-[#212121]">
                <Image src={Facebook} alt="f" className="h-[60%] w-fit" />
                <p>Facebook</p>
              </a>
              <a target="_blank" href={"https://www.instagram.com/tamimmusfik"} className="flex px-2 items-center gap-x-2 w-[90%] m-auto h-10 rounded-md bg-[#212121]">
                <Image src={Instagram} alt="f" className="h-[60%] w-fit" />
                <p>Instagram</p>
              </a>
              <a target="_blank" href={"https://github.com/musfiktamim"} className="flex px-2 items-center gap-x-2 w-[90%] m-auto h-10 rounded-md bg-[#212121]">
                <Image src={GithubIcon} alt="f" className="h-[60%] w-fit" />
                <p>GitHub</p>
              </a>
              <a target="_blank" href={"https://www.fiverr.com/musfiktamim"} className="flex px-2 items-center gap-x-2 w-[90%] m-auto h-10 rounded-md bg-[#212121]">
                <Image src={Fiverfavicon} alt="f" className="h-[60%] w-fit" />
                <p>Fiverr</p>
              </a>
            </div>
          </div>
          <div className="h-[90vh] flex gap-y-2 flex-col w-full">
            <div className="h-12 flex items-center gap-3 md:justify-center justify-between rounded-md bg-[#27272A]">
                <div className="md:hidden h-[100%] w-[50px]">
                  <Image src={Hamburger} alt="hello" className="h-[100%] w-[100px]" />
                </div>
                <div className="flex w-[90%] items-center gap-3 md:justify-center justify-center">
                  <Link href={'/'}>Home</Link>
                  <Link href={'/about'}>About</Link>
                  <Link href={'/project'}>Project</Link>
                  <Link href={'/services'}>Services</Link>
                </div>
            </div>
            <main className="bg-[#27272A] md:h-[100%]  overflow-y-auto h-auto rounded-md">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
